function make_gp_plot(x, m, sd, obs_x, obs_y, bounds, dot_size, ...
                      x_label, obs_label, legend_location, width, height)

  x = x(:);
  m = m(:);
  sd = sd(:);
  sd(isnan(sd)) = 0;
  sd(sd == 0) = eps;
  m(isnan(m)) = 0;
  
  fh = figure;
  
  hold off;
  SDh = fill([x; x(end:-1:1)], ...
             [m + 2 * sd; m(end:-1:1) - 2 * sd(end:-1:1)], ...
             [0.87 0.89 1], 'EdgeColor', 'none');
  hold on;
  observationsh = plot(obs_x, obs_y, '.');
  meanh = plot(x, m);
  
  set(fh, 'units', 'centimeters', ... 
          'NumberTitle', 'off', 'Name', 'plot');
  pos = get(fh, 'position'); 
  set(fh, 'position', [pos(1:2), width, height]); 
  
  axis(bounds)
  
  set(gca, 'TickDir', 'out')
  set(gca, 'Box', 'off', 'FontSize', 10); 
  set(fh, 'color', 'white'); 
  set(gca, 'YGrid', 'off');
  
  set(meanh, ... 
      'LineStyle', '-', ...
      'LineWidth', 2, ...
      'Marker', 'none', ...
      'MarkerSize', 10, ...
      'Color', [0 0 0.8] ...
      );
  
  set(meanh, ... 
      'LineStyle', '-', ...
      'LineWidth', 1, ...
      'Marker', 'none', ...
      'MarkerSize', 10, ...
      'Color', [0 0 0.8] ...
      );
  
  set(observationsh, ... 
      'LineStyle', 'none', ...
      'LineWidth', 0.5, ...
      'Marker', '.', ...
      'MarkerSize', dot_size, ...
      'Color', [0.25 0.25 0.25] ...
      );
  
  xlabel(x_label);
  
  legend( ...
      [observationsh, meanh, SDh], ...
      obs_label, ...
      'mean' , ...
      '+/- 2 SD', ...
      'Location', ...
      legend_location ...
      );
  
  legend boxoff;
end